# Site settings
title: TAKA
description: Just wish me a brand new start of the next few years.
cover: /assets/images/radhakrishna.jpg
#logo: assets/images/logo.png
logo: /assets/images/logo_bear.png
#favicon: assets/images/favicon.png
favicon: /assets/images/Image_213449.jpg
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://t4k4.github.io/" # the base hostname & protocol for your site
future: true

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: t4k4 #github username
repo: t4k4.github.io #github repository
branch: build-branch #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://t4k4.github.io/
#source_url:  https://github.com/samanyougarg/hanuman #source repository url
source_url: https://github.com/t4k4/t4k4.github.io

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml